export { default as Certifications } from "./certifications"
export { default as Education } from "./education"
export { default as Experiences } from "./experiences"
export { default as Gallery } from "./gallery"
export { default as Hobbies } from "./hobbies"
